/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Internalpages;

/**
 *
 * @author SCC-COMLAB
 */
import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;
public class DashBoardPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form DashBoardPage
     */
    public DashBoardPage() {
        initComponents();
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
    BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
    bi.setNorthPane(null);
    }
    Color navcolor = new Color(0,102,102);
    Color navbar = new Color (240,240,240);
    Color Hdcolor = new Color (0,102,102);
    Color buttons = new Color(0,153,153);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(790, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(224, 152, 67));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Welcome User!");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 197, 51));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 0, 760, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rsz_1995e3779e1d2e419a823518c3bdb1298.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(540, 150, 240, 350);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rsz_3rsz_1rsz_1rsz_1se-urban-small-lot-05-1170x1813.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 150, 240, 350);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/rsz_1rsz_3bellwoods-lodge-great-lakes-studio-15.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(280, 150, 230, 350);

        jButton1.setText("INFO");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(360, 510, 57, 23);

        jButton2.setText("INFO");
        jButton2.setOpaque(false);
        jPanel1.add(jButton2);
        jButton2.setBounds(640, 510, 57, 23);

        jButton3.setText("INFO");
        jButton3.setOpaque(false);
        jPanel1.add(jButton3);
        jButton3.setBounds(90, 510, 57, 23);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
