/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Internalpages;
import Internalpages.dbp;
import Internalpages.LoginForm;
import Internalpages.Userpage;
import Internalpages.settings;
import Internalpages.userset;
import config.dpconnector;
import java.awt.Color;
import internalpages.*;
import static java.awt.Color.BLACK;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.ListSelectionModel;
import javax.swing.Timer;


import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.plaf.basic.BasicScrollPaneUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import tumampo.re.design.dashboard;

/**
 *
 * @author ACER
 */
public class gen extends javax.swing.JInternalFrame {

    /**
     * Creates new form gen
     */
    public gen() {
        initComponents();
        displayproperty();
        rid.setVisible(false);
            this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
    BasicInternalFrameUI bi = (BasicInternalFrameUI)this.getUI();
    bi.setNorthPane(null);
    
    }
    Color navcolor = new Color(0,102,102);
    
            public void displayproperty()
    {
        try{
    dpconnector dbc = new dpconnector();
    ResultSet rs = dbc.getData("SELECT r_id as 'Room ID', r_number as 'Room Number', r_address as 'Address', r_type as 'property type', r_status as 'Property Status', r_prise as 'Rent Price' FROM tbl_rooms");
    property_table.setModel(DbUtils.resultSetToTableModel(rs));
    
        }catch(SQLException ex){
        System.out.println("Error Message"); 
        }
    DefaultTableModel model = (DefaultTableModel) property_table.getModel();
        
    TableColumnModel columnModel = property_table.getColumnModel();
    columnModel.getColumn(0).setPreferredWidth(50);
    columnModel.getColumn(1).setPreferredWidth(100);
    columnModel.getColumn(2).setPreferredWidth(150);
    columnModel.getColumn(4).setPreferredWidth(100);
    columnModel.getColumn(5).setPreferredWidth(50);
    property_table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);  
    property_table.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
    property_table.getTableHeader().setOpaque(false);
    property_table.getTableHeader().setBackground(navcolor);
    property_table.getTableHeader().setForeground(BLACK);
    property_table.setRowHeight(25);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rnum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rprice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        raddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        combox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        rtype = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        property_table = new javax.swing.JTable();
        rid = new javax.swing.JLabel();
        panelRound2 = new Internalpages.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(790, 574));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(178, 63, 48));
        jPanel2.setPreferredSize(new java.awt.Dimension(990, 1000));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Property Number");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 110, 30));
        jPanel2.add(rnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 280, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Property Price");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, 30));
        jPanel2.add(rprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 280, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Property Location");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 30));

        raddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raddressActionPerformed(evt);
            }
        });
        jPanel2.add(raddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 280, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Property Status");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 110, 30));

        combox1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        combox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Rented", "Pending", "Under-maintenance" }));
        combox1.setOpaque(false);
        combox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox1ActionPerformed(evt);
            }
        });
        jPanel2.add(combox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, 210, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Property type");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 110, 30));

        rtype.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        rtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "single-family home", "Apartment", "Duplex", "Student" }));
        rtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtypeActionPerformed(evt);
            }
        });
        jPanel2.add(rtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 210, 30));

        property_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        property_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                property_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(property_table);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 710, 220));

        rid.setText("jLabel2");
        jPanel2.add(rid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, -1, -1));

        panelRound2.setBackground(new java.awt.Color(255, 255, 255));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);
        panelRound2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound2MouseClicked(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-clear-45.png"))); // NOI18N
        panelRound2.add(jLabel8);

        jPanel2.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 60, 60));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button (5).png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 140, 60));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 140, 60));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/button (1).png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, 140, 60));

        jScrollPane2.setViewportView(jPanel2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void raddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raddressActionPerformed

    private void combox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combox1ActionPerformed

    private void rtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtypeActionPerformed

    private void property_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_property_tableMouseClicked
        // TODO add your handling code here
        int RowIndex  = property_table.getSelectedRow();
        if(RowIndex < 0){
            JOptionPane.showMessageDialog(null,"Successfully Updated.","Alert",JOptionPane.WARNING_MESSAGE);
        }else{
            TableModel model = property_table.getModel();

            rid.setText(""+model.getValueAt(RowIndex, 0));
            rnum.setText(""+model.getValueAt(RowIndex, 1));
            rprice.setText(""+model.getValueAt(RowIndex, 5));
            raddress.setText(model.getValueAt(RowIndex, 2).toString());
            combox1.setSelectedItem(model.getValueAt(RowIndex, 4).toString());
            rtype.setSelectedItem(model.getValueAt(RowIndex, 3).toString());
            jLabel7.setVisible(false);
        }
    }//GEN-LAST:event_property_tableMouseClicked

    private void panelRound2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound2MouseClicked
        // TODO add your handling code here:
        rnum.setText("");
        rprice.setText("");
        raddress.setText("");
        combox1.setSelectedItem(null);
        rtype.setSelectedItem(null);
        jLabel7.setVisible(true);
    }//GEN-LAST:event_panelRound2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        
        dpconnector dbc = new dpconnector();
        dbc.insertData("INSERT INTO `tbl_rooms`(`r_prise`, `r_status`, `r_number`, `r_address`, `r_type`)"
            + "VALUES ('"+rprice.getText()+"', '"+combox1.getSelectedItem()+"','"+rnum.getText()+"','"+raddress.getText()+"','"+rtype.getSelectedItem()+"')");
        displayproperty();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
                dpconnector dbc = new dpconnector();
        int num = dbc.updateData("UPDATE tbl_rooms "
            + "SET r_prise = '"+rprice.getText()+"', r_status ='"+combox1.getSelectedItem()+"', "
            + "r_number ='"+rnum.getText()+"', r_address='"+raddress.getText()+"', r_type ='"+rtype.getSelectedItem()+"'  "
            + "WHERE r_id = '"+rid.getText()+"'");

        if(num == 0){

        }else{
            JOptionPane.showMessageDialog(null, "Updated Successfully!");
            displayproperty();
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
                int rowindex = property_table.getSelectedRow();
        if(rowindex < 0){
            JOptionPane.showMessageDialog(null, "Please select a data first");
        }else{
            TableModel mode = property_table.getModel();
            Object value = mode.getValueAt(rowindex, 0);
            String i = value.toString();
            int a=JOptionPane.showConfirmDialog(null,"Are you sure?");
            if(a==JOptionPane.YES_OPTION){
                dpconnector db = new dpconnector();
                db.deleteData(Integer.parseInt(i), "tbl_rooms", "r_id");
                displayproperty();

            }

        }
    }//GEN-LAST:event_jLabel10MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private Internalpages.PanelRound panelRound2;
    private javax.swing.JTable property_table;
    private javax.swing.JTextField raddress;
    private javax.swing.JLabel rid;
    private javax.swing.JTextField rnum;
    private javax.swing.JTextField rprice;
    private javax.swing.JComboBox<String> rtype;
    // End of variables declaration//GEN-END:variables
}
