/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Internalpages;

import config.dpconnector;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.Area;
import java.awt.geom.Rectangle2D;
import java.awt.geom.RoundRectangle2D;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ACER
 */
public class newuser extends javax.swing.JFrame {

    /**
     * Creates new form newuser
     */
    public newuser() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    String gender;
    String Stat;
    String action;
    public String destination = "";
    File selectedFile;
    public String imgPath;
    public String path;

    public ImageIcon ResizeImage(String imagePath) {
        ImageIcon myImage = null;
        if (imagePath != null) {
            myImage = new ImageIcon(imagePath);
        }
        Image img = myImage.getImage().getScaledInstance(imagelabel.getWidth(), imagelabel.getHeight(), Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }

    public void picture() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("C:/Users/User/Pictures"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File SelectedFile = fileChooser.getSelectedFile();
            path = SelectedFile.getAbsolutePath();
            imagelabel.setIcon(ResizeImage(path));
            imgPath = path;
            //assigning file destination
            String destinationFolder = "src/Image";
            //getting the name of the file use
            String fileName = SelectedFile.getName();
            Path destinationPath = Paths.get(destinationFolder, fileName);
            try {
                Files.copy(SelectedFile.toPath(), destinationPath, StandardCopyOption.REPLACE_EXISTING);
                imgPath = destinationPath.toString();
                JOptionPane.showMessageDialog(null, "File saved successfully!");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error occurred while saving the file: " + e.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Canceled!");
        }
    }
//    File F = null;
//    String path = null;
//    private ImageIcon Format = null;
//    int s = 0;
//    byte [] pimage = null;
//    public byte[] imageBytes;
//    Connection conn = null;
//    String filename=null;
//    String imgPath = null;
//   byte[] person_image = null; 
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//       public  ImageIcon ResizeImage(String ImagePath, byte[] pic) {
//    ImageIcon MyImage = null;
//        if(ImagePath !=null){
//            MyImage = new ImageIcon(ImagePath);
//        }else{
//            MyImage = new ImageIcon(pic);
//        }
//    Image img = MyImage.getImage();
//    Image newImg = img.getScaledInstance(imagelabel.getWidth(), imagelabel.getHeight(), Image.SCALE_SMOOTH);
//    ImageIcon image = new ImageIcon(newImg);
//    return image;
//}

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        surname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        x_address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        x_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        x_contact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        combobox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelRound1 = new Internalpages.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        imagelabel = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-40, 0, 30, 550);

        jPanel3.setBackground(new java.awt.Color(188, 71, 58));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(224, 152, 67));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("TENANT REGESTRATION FORM ");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 50));

        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 30));

        jLabel2.setText("Surname");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 90, -1));

        surname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameActionPerformed(evt);
            }
        });
        jPanel6.add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 210, 30));
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, 20));

        x_address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(x_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 210, 30));

        jLabel4.setText("First name");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setText("Address");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 90, 20));

        x_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(x_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 30));

        jLabel6.setText("Email ");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        x_contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        x_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_contactActionPerformed(evt);
            }
        });
        jPanel6.add(x_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 220, 30));

        jLabel8.setText("Password");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jButton2.setText("save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 80, 40));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 80, 40));

        jLabel9.setText("Mobile Number");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 216, -1, 10));

        password1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 220, 30));

        male.setText(" Male ");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel6.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 60, 30));

        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel6.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 80, 30));

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married", "Divorced", "Widow" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });
        jPanel6.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 160, 30));

        jLabel12.setText("jLabel12");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 140, 110));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 470, 530));

        jPanel4.setBackground(new java.awt.Color(224, 152, 67));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 30, 470));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel10.setText("Home");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 190, 100));

        jLabel11.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel11.setText("\"");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 50, 50));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("INSERT IMAGE ");
        panelRound1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 34));
        panelRound1.add(imagelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 170, 140));

        jPanel3.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 230, 240));

        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton3.setText("Choose a File");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 120, -1));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 800, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameActionPerformed

    private void x_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x_contactActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String hashedpass = null;
        if (fname.getText() == null || fname.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "First Name cannot be blank. Please Fill in.",
                    "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (surname.getText() == null || surname.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Surname cannot be blank. Please Fill in.",
                    "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (x_email.getText() == null || x_email.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Email cannot be blank. Please Fill in.",
                    "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (x_address.getText() == null || x_address.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Address cannot be blank. Please Fill in.",
                    "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (x_contact.getText() == null || x_contact.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Number cannot be blank. Please Fill in.",
                    "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (password1.getText() == null || password1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password cannot be blank. Please Fill in.",
                    "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (password1.getText().length() < 8) {
            JOptionPane.showMessageDialog(null, "Password is too short. Please enter a password that is at least 8 characters long.",
                    "Error!", JOptionPane.ERROR_MESSAGE);
        } else {

            try {
                MessageDigest md = MessageDigest.getInstance("SHA-256");
                md.update(password1.getText().getBytes());
                byte[] byteData = md.digest();
                StringBuffer sb = new StringBuffer();
                for (int i = 0; i < byteData.length; i++) {
                    sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
                }
                hashedpass = sb.toString();
            } catch (NoSuchAlgorithmException e) {
                e.printStackTrace();
            }
//            String n = "INSERT INTO `tb_user`(`u_id`, `u_fname`, `u_Lname`, `u_email`, `u_num`, `u_pass`, `u_address`, `image_path`)";
            dpconnector dbc = new dpconnector();
            dbc.insertData("INSERT INTO tb_user (u_fname, u_Lname, u_email, u_num, u_gender, u_status, u_address, u_pass, image_path) "
                    + "VALUES ('" + fname.getText() + "', '" + surname.getText() + "','" + x_email.getText() + "',"
                    + "'" + x_contact.getText() + "','" + gender + "','" + combobox.getSelectedItem() + "','" + x_address.getText() + "','" + hashedpass + "','" + path + "')");

            JOptionPane.showMessageDialog(null, "Successfully Registered",
                    "MESSAGE!", JOptionPane.INFORMATION_MESSAGE);
            LoginForm L = new LoginForm();
            L.setVisible(true);
            this.dispose();

        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1ActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        if (male.isSelected()) {
            female.setSelected(false);
            gender = "Male";
        } else {
            gender = null;
        }
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        male.setSelected(false);
        if (female.isSelected()) {
            male.setSelected(false);
            gender = "Female";

        } else {
            gender = null;
        }
    }//GEN-LAST:event_femaleActionPerformed

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboboxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        picture();

//        // TODO add your handling code here:
//        JFileChooser chooser = new JFileChooser();
//        chooser.setCurrentDirectory(new File(System.getProperty("user.home")));
//        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg", "gif", "png");
//        chooser.addChoosableFileFilter(filter);
//        int result = chooser.showSaveDialog(null);
//        
//        if (result == JFileChooser.APPROVE_OPTION){
//            File selectedFile = chooser.getSelectedFile();
//            path = selectedFile.getAbsolutePath();
//            imagelabel.setIcon(ResizeImage(path,null));
//            imgPath = path;
//            File f = chooser.getSelectedFile();
//            filename = selectedFile.getAbsolutePath();
//        }else{
//        JOptionPane.showMessageDialog(null, "Canceled !");
//        }
//        
//      
//        try {
//                File image = new File(filename);
//                FileInputStream fis = new FileInputStream(image);
//                ByteArrayOutputStream bos = new ByteArrayOutputStream();
//                byte[] buf = new byte[1024];
//                
//                for (int readNum; (readNum=fis.read(buf)) !=-1;){
//                 bos.write(buf,0,readNum);
//                }
//                person_image=bos.toByteArray();
//                
//        }catch(Exception e){
//            System.out.println(e);
//        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> combobox;
    public javax.swing.JRadioButton female;
    public javax.swing.JTextField fname;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JRadioButton male;
    private Internalpages.PanelRound panelRound1;
    private javax.swing.JPasswordField password1;
    public javax.swing.JTextField surname;
    public javax.swing.JTextField x_address;
    public javax.swing.JTextField x_contact;
    public javax.swing.JTextField x_email;
    // End of variables declaration//GEN-END:variables
}
