/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Internalpages;
import config.dpconnector;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
/**
 *
 * @author ACER
 */
public class newuser extends javax.swing.JFrame {

    /**
     * Creates new form newuser
     */
    public newuser() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        surname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        x_address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        x_email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        x_contact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-40, 0, 30, 550);

        jPanel3.setBackground(new java.awt.Color(188, 71, 58));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(224, 152, 67));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("TENANT REGESTRATION FORM ");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 50));

        fname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, 30));

        jLabel2.setText("Surname");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 90, -1));

        surname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameActionPerformed(evt);
            }
        });
        jPanel6.add(surname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 210, 30));
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, 20));

        x_address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(x_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 210, 30));

        jLabel4.setText("First name");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setText("Address");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 90, 20));

        x_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(x_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 30));

        jLabel6.setText("Email ");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        x_contact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        x_contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x_contactActionPerformed(evt);
            }
        });
        jPanel6.add(x_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 220, 30));

        jLabel8.setText("Password");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jButton2.setText("save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 80, 40));

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 80, 40));

        jLabel9.setText("Mobile Number");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 216, -1, 10));

        password1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.add(password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 220, 30));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 470, 530));

        jPanel4.setBackground(new java.awt.Color(224, 152, 67));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 30, 450));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel10.setText("Home");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 190, 100));

        jLabel11.setFont(new java.awt.Font("Stencil", 1, 48)); // NOI18N
        jLabel11.setText("\"");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 50, 50));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 800, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 808, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameActionPerformed

    private void x_contactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x_contactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x_contactActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String hashedpass = null;
        if (fname.getText() == null || fname.getText().trim().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "First Name cannot be blank. Please Fill in.",
      "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (surname.getText() == null || surname.getText().trim().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Surname cannot be blank. Please Fill in.",
      "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (x_email.getText() == null || x_email.getText().trim().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Email cannot be blank. Please Fill in.",
      "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (x_address.getText() == null || x_address.getText().trim().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Address cannot be blank. Please Fill in.",
      "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (x_contact.getText() == null || x_contact.getText().trim().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Number cannot be blank. Please Fill in.",
      "Error!", JOptionPane.ERROR_MESSAGE);
        }
        if (password1.getText() == null || password1.getText().trim().isEmpty()) { 
            JOptionPane.showMessageDialog(null, "Password cannot be blank. Please Fill in.",
      "Error!", JOptionPane.ERROR_MESSAGE);
        }                    
        if (password1.getText().length() < 8) {
              JOptionPane.showMessageDialog(null, "Password is too short. Please enter a password that is at least 8 characters long.",
       "Error!", JOptionPane.ERROR_MESSAGE);
        }else {

        try{
             MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(password1.getText().getBytes());
            byte[] byteData = md.digest();
            StringBuffer sb = new StringBuffer();
                for (int i = 0; i < byteData.length; i++) {
                  sb.append(Integer.toString((byteData[i] & 0xff) + 0x100, 16).substring(1));
                   }
                hashedpass = sb.toString();
        }catch(NoSuchAlgorithmException e){
            e.printStackTrace();
        }
        dpconnector dbc = new dpconnector();
                dbc.insertData("INSERT INTO tb_user (u_fname, u_Lname, u_email, u_num,  u_address, u_pass) "
                + "VALUES ('"+fname.getText()+"', '"+surname.getText()+"','"+x_email.getText()+"',"
                        + "'"+x_contact.getText()+"','"+x_address.getText()+"','"+hashedpass+"')");
                
        JOptionPane.showMessageDialog(null, "Successfully Registered",
       "MESSAGE!", JOptionPane.INFORMATION_MESSAGE); 
        LoginForm L = new LoginForm();
        L.setVisible(true);
        this.dispose();
        
              }

        
 

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField password1;
    public javax.swing.JTextField surname;
    public javax.swing.JTextField x_address;
    public javax.swing.JTextField x_contact;
    private javax.swing.JTextField x_email;
    // End of variables declaration//GEN-END:variables
}
