/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Internalpages;

/**
 *
 * @author ACER
 */
public class prints extends javax.swing.JFrame {

    /**
     * Creates new form prints
     */
    public prints() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        FNAMES = new javax.swing.JLabel();
        LNAME = new javax.swing.JLabel();
        ADDRESS = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        GENDER = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CIVIL = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        CON = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        EMAIL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(204, 102, 0));
        jPanel5.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(460, 90, 470, 540);

        jPanel6.setBackground(new java.awt.Color(178, 63, 48));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(10, 0, 10, 660);

        jPanel7.setBackground(new java.awt.Color(178, 63, 48));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel7);
        jPanel7.setBounds(0, 10, 950, 10);

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setText("PRINT");
        jPanel5.add(jButton1);
        jButton1.setBounds(140, 590, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRINT TENANT INFO");
        jPanel5.add(jLabel1);
        jLabel1.setBounds(590, 40, 220, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("___________________");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(580, 0, 250, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("___________________");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(580, 40, 250, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("EMAIL ADDRESS  :");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(40, 320, 130, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ID                           :");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(40, 110, 130, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("FRIST NAME         :");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(40, 140, 140, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("LAST NAME          :");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(40, 170, 130, 20);

        ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(ID);
        ID.setBounds(180, 110, 180, 20);

        FNAMES.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(FNAMES);
        FNAMES.setBounds(180, 140, 180, 20);

        LNAME.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(LNAME);
        LNAME.setBounds(180, 170, 180, 20);

        ADDRESS.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(ADDRESS);
        ADDRESS.setBounds(180, 200, 180, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ADDRESS              :");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(40, 200, 130, 20);

        GENDER.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(GENDER);
        GENDER.setBounds(180, 230, 180, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("GENDER                :");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(40, 230, 130, 20);

        CIVIL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(CIVIL);
        CIVIL.setBounds(180, 260, 180, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("CIVIL STATUS     :");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(40, 260, 130, 20);

        CON.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(CON);
        CON.setBounds(180, 290, 180, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("CONTACT NO.      :");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(40, 290, 130, 20);

        EMAIL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel5.add(EMAIL);
        EMAIL.setBounds(180, 320, 180, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prints.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prints().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ADDRESS;
    public javax.swing.JLabel CIVIL;
    public javax.swing.JLabel CON;
    public javax.swing.JLabel EMAIL;
    public javax.swing.JLabel FNAMES;
    public javax.swing.JLabel GENDER;
    public javax.swing.JLabel ID;
    public javax.swing.JLabel LNAME;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    void FNAME(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
