/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Internalpages;

import config.dpconnector;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import tumampo.re.design.dashboard;

/**
 *
 * @author ACER
 */
public class property extends javax.swing.JFrame {

    /**
     * Creates new form property
     */
    public property() {
        
        initComponents();
        displayproperty();
    }
        public void displayproperty()
    {
        try{
    dpconnector dbc = new dpconnector();
    ResultSet rs = dbc.getData("SELECT * FROM tbl_rooms");
    property_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException ex){
        System.out.println("Error Message");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rnum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rprice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        combox1 = new javax.swing.JComboBox<>();
        rtype = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        raddress = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        property_table = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        rid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(224, 152, 67));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("House type");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 380, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("House Number");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 80, 110, 30);
        jPanel1.add(rnum);
        rnum.setBounds(130, 120, 280, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("House Price");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 170, 100, 30);
        jPanel1.add(rprice);
        rprice.setBounds(130, 170, 280, 30);

        jButton1.setBackground(new java.awt.Color(161, 197, 53));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(330, 440, 80, 30);

        combox1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        combox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Rented", "Pending", "Under-maintenance" }));
        combox1.setOpaque(false);
        combox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox1ActionPerformed(evt);
            }
        });
        jPanel1.add(combox1);
        combox1.setBounds(130, 340, 280, 30);
        combox1.getAccessibleContext().setAccessibleDescription("");

        rtype.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        rtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "single-family home", "Apartment", "Duplex", "Student" }));
        rtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtypeActionPerformed(evt);
            }
        });
        jPanel1.add(rtype);
        rtype.setBounds(130, 380, 280, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("House Location");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 210, 110, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("House Status");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 340, 110, 30);

        raddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raddressActionPerformed(evt);
            }
        });
        jPanel1.add(raddress);
        raddress.setBounds(130, 220, 280, 110);

        jPanel2.setBackground(new java.awt.Color(178, 63, 48));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(161, 197, 53));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 90, 30));

        jButton3.setBackground(new java.awt.Color(236, 24, 1));
        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 90, 30));

        jButton4.setBackground(new java.awt.Color(161, 197, 53));
        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 90, 30));

        property_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        property_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                property_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(property_table);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 630, 380));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 30));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(420, 10, 650, 460);
        jPanel1.add(rid);
        rid.setBounds(130, 80, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("House Number");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 120, 110, 30);

        jButton5.setText("Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(240, 440, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1081, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dpconnector dbc = new dpconnector();
        dbc.insertData("INSERT INTO tbl_rooms (r_prise, r_status, r_number ) "
                + "VALUES ('"+rprice.getText()+"', '"+combox1.getSelectedItem()+"','"+rnum.getText()+"')");
        displayproperty();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        displayproperty();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       int rowindex = property_table.getSelectedRow();      
       if(rowindex < 0){
           JOptionPane.showMessageDialog(null, "Please select a data first");
       }else{
            TableModel mode = property_table.getModel();
            Object value = mode.getValueAt(rowindex, 0);
            String i = value.toString();
             int a=JOptionPane.showConfirmDialog(null,"Are you sure?");  
                    if(a==JOptionPane.YES_OPTION){  
                            dpconnector db = new dpconnector();
                            db.deleteData(Integer.parseInt(i), "tbl_rooms", "r_id");
                            displayproperty();
                     
                    }    
       
       }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
dpconnector dbc = new dpconnector();
        int num = dbc.updateData("UPDATE tbl_rooms "
                + "SET r_prise = '"+rprice.getText()+"', r_status ='"+combox1.getSelectedItem()+"', "
                        + "r_number ='"+rnum.getText()+"', r_address='"+raddress.getText()+"', r_type ='"+rtype.getSelectedItem()+"'  "
                                + "WHERE r_id = '"+rid.getText()+"'");
       
        if(num == 0){
           
        }else{
           JOptionPane.showMessageDialog(null, "Updated Successfully!");
           displayproperty();
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void combox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combox1ActionPerformed

    private void rtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtypeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        dashboard dash =new dashboard();
        dash.setVisible(true);
        settings up = new settings();
        dash.maindesktop.add(up).setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void raddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_raddressActionPerformed

    private void property_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_property_tableMouseClicked
        // TODO add your handling code here
        int RowIndex  = property_table.getSelectedRow();
        if(RowIndex < 0){
        JOptionPane.showMessageDialog(null,"Successfully Updated.","Alert",JOptionPane.WARNING_MESSAGE); 
        }else{
        TableModel model = property_table.getModel();
         
         rid.setText(""+model.getValueAt(RowIndex, 0));
         rnum.setText(""+model.getValueAt(RowIndex, 3));
         rprice.setText(""+model.getValueAt(RowIndex, 1));
         raddress.setText(model.getValueAt(RowIndex, 4).toString());
         combox1.setSelectedItem(model.getValueAt(RowIndex, 2).toString());
         rtype.setSelectedItem(model.getValueAt(RowIndex, 5).toString());
        }
    }//GEN-LAST:event_property_tableMouseClicked

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:\
        DefaultTableModel model = (DefaultTableModel) property_table.getModel();
        TableRowSorter<DefaultTableModel> tbl = new TableRowSorter<>(model);
        property_table.setRowSorter(tbl);
        
        String searchText = jTextField1.getText().trim();
        tbl.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
        
        int selectedRow = property_table.getSelectedRow();
        if(selectedRow != -1 ){
        int modelRow = property_table.convertColumnIndexToModel(selectedRow);
        model.setValueAt("New Value", modelRow, 1);
        }
        displayproperty();
    }//GEN-LAST:event_jTextField1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(property.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(property.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(property.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(property.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new property().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combox1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable property_table;
    private javax.swing.JTextField raddress;
    private javax.swing.JTextField rid;
    private javax.swing.JTextField rnum;
    private javax.swing.JTextField rprice;
    private javax.swing.JComboBox<String> rtype;
    // End of variables declaration//GEN-END:variables
}
